title: 'Development Anrinch Entertainment'

transporter:
  default:
    host: 'smtp.gmail.com'
    port: 587
    secure: false # true for 465, false for other ports
    auth:
      user: 'p.d.walczak@gmail.com' # generated ethereal user
      pass: 'xderosmorynsxjbj' # generated ethereal password

mailer:
  default:
    from: '"anrinch.com" <noreply@anrinch.com>'

sass:
  outputStyle: 'expanded'

# http:
#   host: 192.168.0.18
#   port: 3000
